// Generated by df-prism/tools/emit-tailwind.mjs from examples/designframe/exports/tokens.json.
// DO NOT EDIT — re-run the emitter (`node tools/emit-tailwind.mjs`) to update.
// Scope: token-subset (theme.screens + theme.extend.{colors,spacing,fontFamily,borderRadius}).
// Source tokens: Designframe v0.99.0 via Prism v1-export.
// Lossiness: opacity-modifier CSS-var indirection + grid/flex utility surface
// are out of scope per manifest.lossiness (color-source-form, adaptive-stacks).

module.exports = {
  "theme": {
    "screens": {
      "sm": "640px",
      "md": "768px",
      "lg": "960px",
      "xl": "1440px",
      "2xl": "1600px"
    },
    "extend": {
      "colors": {
        "key": "#222222",
        "key-end": "#222222",
        "primary": "#0c0c0c",
        "secondary": "#757575",
        "tertiary": "#cccccc",
        "invert": "#ffffff",
        "disabled": "#cccccc",
        "background": "#ffffff",
        "background-start": "#dddddd",
        "background-end": "#ffffff",
        "key-alt": "#000000",
        "key-end-alt": "#222222",
        "primary-alt": "#0c0c0c",
        "secondary-alt": "#757575",
        "tertiary-alt": "#cccccc",
        "invert-alt": "#ffffff",
        "disabled-alt": "#cccccc",
        "background-alt": "#ffffff",
        "background-start-alt": "#cccccc",
        "background-end-alt": "#ffffff",
        "alert": {
          "notify": {
            "DEFAULT": "#60a5fa",
            "h": "#1d4ed8",
            "p": "#2563eb",
            "bg": "#dbeafe"
          },
          "warning": {
            "DEFAULT": "#facc15",
            "h": "#a16207",
            "p": "#ca8a04",
            "bg": "#fef9c3"
          },
          "error": {
            "DEFAULT": "#f87171",
            "h": "#b91c1c",
            "p": "#dc2626",
            "bg": "#fee2e2"
          },
          "success": {
            "DEFAULT": "#4ade80",
            "h": "#15803d",
            "p": "#16a34a",
            "bg": "#dcfce7"
          }
        },
        "theme": {
          "default": {
            "bg": "#ffffff",
            "fg": "#0c0c0c"
          },
          "invert": {
            "bg": "#0c0c0c",
            "fg": "#ffffff"
          },
          "key": {
            "bg": "#222222",
            "fg": "#ffffff"
          },
          "default-transparent": {
            "bg": "transparent",
            "fg": "#0c0c0c"
          },
          "alt": {
            "bg": "#ffffff",
            "fg": "#0c0c0c"
          },
          "alt-transparent": {
            "bg": "transparent",
            "fg": "#0c0c0c"
          },
          "invert-transparent": {
            "bg": "transparent",
            "fg": "#ffffff"
          },
          "alt-invert": {
            "bg": "#0c0c0c",
            "fg": "#ffffff"
          },
          "alt-invert-transparent": {
            "bg": "transparent",
            "fg": "#ffffff"
          },
          "key-gradient": {
            "bg": "#222222",
            "bg-start": "#222222",
            "bg-end": "#222222",
            "fg": "#ffffff"
          },
          "key-alt": {
            "bg": "#000000",
            "fg": "#ffffff"
          },
          "key-alt-gradient": {
            "bg": "#000000",
            "bg-start": "#000000",
            "bg-end": "#222222",
            "fg": "#ffffff"
          },
          "header": {
            "bg": "#ffffff",
            "fg": "#0c0c0c",
            "nav-link": "#757575"
          },
          "footer": {
            "bg": "#ffffff",
            "fg": "#0c0c0c",
            "nav-link": "#757575"
          }
        },
        "fg": {
          "default": "#0c0c0c",
          "muted": "#757575",
          "subtle": "#cccccc",
          "on-key": "#ffffff",
          "on-dark": "#ffffff",
          "disabled": "#cccccc"
        },
        "bg": {
          "canvas": "#ffffff",
          "key": "#222222",
          "key-start": "#222222",
          "key-end": "#222222",
          "invert": "#0c0c0c"
        }
      },
      "spacing": {
        "unit": "4px",
        "gutter": "24px",
        "gutter-xl": "32px",
        "gutter-2xl": "32px",
        "shoulder": "24px",
        "shoulder-sm": "32px",
        "shoulder-md": "36px",
        "shoulder-lg": "36px",
        "shoulder-xl": "40px",
        "shoulder-2xl": "48px",
        "article": "16px",
        "article-xl": "24px",
        "element": "16px",
        "section": "48px",
        "section-xl": "64px",
        "header": "12px",
        "header-xl": "16px",
        "stack": "16px",
        "form": "12px",
        "form-xl": "16px",
        "sub": "8px",
        "sub-xl": "12px",
        "hgroup-display": "16px",
        "hgroup-heading": "8px",
        "hgroup-title": "4px",
        "md": "24px",
        "sm": "16px",
        "xs": "8px",
        "2xs": "4px"
      },
      "fontFamily": {
        "heading": [
          "headingFontFamily",
          "sans-serif",
          "system-ui"
        ],
        "body": [
          "bodyFontFamily",
          "sans-serif",
          "system-ui"
        ],
        "display": [
          "displayFontFamily",
          "sans-serif",
          "system-ui"
        ]
      },
      "borderRadius": {
        "min": "4px",
        "base": "0px",
        "corner": "4px",
        "field": "4px",
        "full": "9999px",
        "chip": "4px",
        "article": "16px",
        "article-xl": "24px"
      }
    }
  }
};
