// Generated by df-prism/tools/emit-tailwind.mjs from examples/designframe/exports/tokens.json.
// DO NOT EDIT — re-run the emitter (`node tools/emit-tailwind.mjs`) to update.
// Scope: token-subset (theme.screens + theme.extend.{colors,spacing,fontFamily,borderRadius}).
// Source tokens: Designframe v0.99.0 via Prism v1-export.
// Lossiness: opacity-modifier CSS-var indirection + grid/flex utility surface
// are out of scope per manifest.lossiness (color-source-form, adaptive-stacks).

module.exports = {
  "theme": {
    "screens": {
      "sm": "640px",
      "md": "768px",
      "lg": "960px",
      "xl": "1440px",
      "2xl": "1600px"
    },
    "extend": {
      "colors": {
        "key": "#fb03b9",
        "key-end": "#3883ff",
        "primary": "#0c0c0c",
        "secondary": "#888888",
        "tertiary": "#cccccc",
        "invert": "#ffffff",
        "disabled": "#cccccc",
        "background": "#ffffff",
        "background-start": "#ffe6f8",
        "background-end": "#ebf3ff",
        "key-alt": "#fa0002",
        "key-end-alt": "#faa002",
        "primary-alt": "#0c0c0c",
        "secondary-alt": "#888888",
        "tertiary-alt": "#cccccc",
        "invert-alt": "#ffffff",
        "disabled-alt": "#cccccc",
        "background-alt": "#ffffff",
        "background-start-alt": "#ff9f1c",
        "background-end-alt": "#ffd166",
        "alert": {
          "notify": {
            "DEFAULT": "#3883ff",
            "fg": "#ffffff"
          },
          "warning": {
            "DEFAULT": "#faa002",
            "fg": "#0c0c0c"
          },
          "error": {
            "DEFAULT": "#fa0002",
            "fg": "#ffffff"
          },
          "success": {
            "DEFAULT": "#22c55e",
            "fg": "#ffffff"
          }
        },
        "theme": {
          "default": {
            "bg": "#ffffff",
            "fg": "#0c0c0c"
          },
          "invert": {
            "bg": "#0c0c0c",
            "fg": "#ffffff"
          },
          "key": {
            "bg": "#fb03b9",
            "fg": "#ffffff"
          },
          "default-transparent": {
            "bg": "transparent",
            "fg": "#0c0c0c"
          },
          "alt": {
            "bg": "#ffffff",
            "fg": "#0c0c0c"
          },
          "alt-transparent": {
            "bg": "transparent",
            "fg": "#0c0c0c"
          },
          "invert-transparent": {
            "bg": "transparent",
            "fg": "#ffffff"
          },
          "alt-invert": {
            "bg": "#0c0c0c",
            "fg": "#ffffff"
          },
          "alt-invert-transparent": {
            "bg": "transparent",
            "fg": "#ffffff"
          },
          "key-gradient": {
            "bg": "#fb03b9",
            "bg-start": "#fb03b9",
            "bg-end": "#3883ff",
            "fg": "#ffffff"
          },
          "key-alt": {
            "bg": "#fa0002",
            "fg": "#ffffff"
          },
          "key-alt-gradient": {
            "bg": "#fa0002",
            "bg-start": "#fa0002",
            "bg-end": "#faa002",
            "fg": "#ffffff"
          },
          "header": {
            "bg": "#ffffff",
            "fg": "#0c0c0c",
            "nav-link": "#888888"
          },
          "footer": {
            "bg": "#ffffff",
            "fg": "#0c0c0c",
            "nav-link": "#888888"
          }
        },
        "fg": {
          "default": "#0c0c0c",
          "muted": "#888888",
          "subtle": "#cccccc",
          "on-key": "#ffffff",
          "on-dark": "#ffffff",
          "disabled": "#cccccc"
        },
        "bg": {
          "canvas": "#ffffff",
          "key": "#fb03b9",
          "key-start": "#fb03b9",
          "key-end": "#3883ff",
          "invert": "#0c0c0c"
        }
      },
      "spacing": {
        "unit": "4px",
        "gutter": "24px",
        "gutter-xl": "32px",
        "gutter-2xl": "32px",
        "shoulder": "24px",
        "shoulder-sm": "32px",
        "shoulder-md": "36px",
        "shoulder-lg": "36px",
        "shoulder-xl": "40px",
        "shoulder-2xl": "48px",
        "article": "16px",
        "article-xl": "24px",
        "element": "16px",
        "section": "48px",
        "section-xl": "64px",
        "header": "12px",
        "header-xl": "16px",
        "stack": "16px",
        "form": "12px",
        "form-xl": "16px",
        "sub": "8px",
        "sub-xl": "12px",
        "hgroup-display": "16px",
        "hgroup-heading": "8px",
        "hgroup-title": "4px",
        "md": "24px",
        "sm": "16px",
        "xs": "8px",
        "2xs": "4px"
      },
      "fontFamily": {
        "heading": [
          "headingFontFamily",
          "sans-serif",
          "system-ui"
        ],
        "body": [
          "bodyFontFamily",
          "sans-serif",
          "system-ui"
        ],
        "display": [
          "displayFontFamily",
          "sans-serif",
          "system-ui"
        ]
      },
      "borderRadius": {
        "min": "4px",
        "base": "8px",
        "corner": "8px",
        "field": "20px",
        "full": "9999px",
        "chip": "4px",
        "article": "16px",
        "article-xl": "24px"
      }
    }
  }
};
